### ISSUE TITLE
Split into lib and cli crates 

### ISSUE THREAD

**Issue by simonvandel** [sunng87/datafusion-postgres#21]
Hi @sunng87

Would you accept a PR that splits this project into 2 crates?

For example something like:
- datafusion-postgres. This would be everything not related to cli handling. It could be used as part of the consumers own binary project.
- datafusion-postgres-cli. This would depend on the above lib, and additionally cli crates like structopt.

**Comment by sunng87** [comment]
Yes. That's exact what I planed to do. Please send the PR for this, thanks!

**Comment by simonvandel** [comment]
> Yes. That's exact what I planed to do. Please send the PR for this, thanks!

I have attempted this in #22
